#!/usr/bin/env python3
"""
autonomous_game_pipeline.py
Pipeline tự động hoá luồng phát triển H5 Mini-Game với GLM-5.3 & OpenCode:
1. GLM-5.3 sinh ý tưởng game & PRD/Prompt chuyên sâu.
2. Hermes thẩm định cấu trúc & phát sinh master execution prompt hoàn chỉnh.
3. OpenCode (GLM-5.3) triển khai code hoàn chỉnh vào thư mục `games/<game-slug>/`.
4. Pipeline tự động verify code (lint/compile/syntax check).
5. Tự động commit & push lên GitHub repository https://github.com/minhgv/glm-h5-game.
6. Cập nhật bảng tổng kết game tại README.md.
"""

import os
import sys
import json
import re
import subprocess
import datetime

REPO_DIR = "/home/minhgv/code/github/glm-h5-game"
OPENCODE_BIN = "/home/minhgv/.local/bin/opencode"

def run_cmd(cmd, cwd=REPO_DIR):
    print(f"[*] Executing: {cmd} (cwd: {cwd})")
    res = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    if res.returncode != 0:
        print(f"[!] Warning/Error in command: {res.stderr.strip()}")
    return res.stdout.strip(), res.returncode

def main():
    print("=== [1/5] Khởi động GLM-5.3 đề xuất Ý Tưởng & Master Prompt ===")
    idea_prompt = (
        "Đề xuất 1 ý tưởng game H5 arcade/casual độc đáo, gây nghiện cao (Theme Đông Nam Á/Việt Nam hoặc Cyberpunk/Sci-Fi), "
        "kèm gameplay loop, cơ chế physics/scoring, audio WebAudio procedural. "
        "Hãy xuất ra định dạng JSON duy nhất với 3 trường: "
        "'slug' (chuỗi không dấu, ví dụ: 'pho-master', 'cyber-saigon-runner'), "
        "'title' (tên game), 'genre' (thể loại), 'description' (mô tả ngắn), "
        "'master_prompt' (Prompt chi tiết Production-Ready đầy đủ code specs để OpenCode dựng 1 game độc lập trong 1 file index.html gồm cả HTML, CSS, JS, WebAudio SFX, Canvas/DOM animation)."
    )
    
    # Gọi OpenCode để lấy output từ GLM-5.3
    raw_output, ret = run_cmd(f"{OPENCODE_BIN} run \"{idea_prompt}\" --model zai-coding-plan/glm-5.3")
    print(f"[+] Output từ GLM-5.3: \n{raw_output[:500]}...\n")
    
    # Trích xuất JSON từ output
    json_match = re.search(r'```json\s*(\{.*?\})\s*```', raw_output, re.DOTALL)
    if not json_match:
        json_match = re.search(r'(\{[\s\S]*\})', raw_output)
    
    if json_match:
        try:
            data = json.loads(json_match.group(1))
            slug = data.get("slug", "game-" + datetime.datetime.now().strftime("%Y%m%d%H%M%S"))
            title = data.get("title", "Mini Game")
            genre = data.get("genre", "Arcade")
            description = data.get("description", "")
            master_prompt = data.get("master_prompt", "")
        except Exception as e:
            print(f"[!] JSON parsing failed: {e}. Sử dụng fallback parser.")
            slug = "pho-ninja-" + datetime.datetime.now().strftime("%Y%m%d")
            title = "Phở Ninja Strike"
            genre = "Action Arcade"
            description = "Game chặt chém nguyên liệu phở phong cách Ninja"
            master_prompt = raw_output
    else:
        slug = "game-arcade-" + datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        title = "Arcade Challenge"
        genre = "Casual"
        description = "Casual mini game"
        master_prompt = raw_output

    game_dir = os.path.join(REPO_DIR, "games", slug)
    os.makedirs(game_dir, exist_ok=True)
    print(f"=== [2/5] Tạo thư mục game: {game_dir} ===")
    
    # Lưu file PROMPT.md
    with open(os.path.join(game_dir, "PROMPT.md"), "w", encoding="utf-8") as f:
        f.write(f"# Prompt & PRD: {title}\n\n**Genre:** {genre}\n**Generated by:** GLM-5.3\n\n## Master Prompt:\n```text\n{master_prompt}\n```\n")

    print(f"=== [3/5] Hermes thẩm định & Ra lệnh OpenCode (GLM-5.3) code game ===")
    execution_instruction = (
        f"Hãy tạo một mini game H5 hoàn chỉnh chạy độc lập trong file `{game_dir}/index.html`. "
        f"Game: {title} ({genre}). "
        f"Yêu cầu: "
        f"1. Toàn bộ HTML, CSS (giao diện hiện đại, responsive mobile/desktop), JS gameplay, WebAudio SFX (procedural oscillator) tích hợp đầy đủ trong file index.html này. "
        f"2. Đạt chuẩn 60fps, touch & mouse friendly, có cơ chế tính điểm, Highscore lưu vào localStorage, Particle VFX hoặc animation mượt mà. "
        f"3. Không sử dụng thư viện ngoài qua CDN nếu không cần thiết, tự code Canvas 2D hoặc DOM Game loop sạch sẽ, không lỗi runtime. "
        f"Tham khảo master prompt: {master_prompt[:1500]}"
    )
    
    opencode_build_cmd = f"{OPENCODE_BIN} run \"{execution_instruction}\" --model zai-coding-plan/glm-5.3"
    build_output, build_ret = run_cmd(opencode_build_cmd, cwd=game_dir)
    print(f"[+] Kết quả build từ OpenCode:\n{build_output[:400]}...\n")

    # Kiểm tra xem file index.html đã được tạo chưa
    index_file = os.path.join(game_dir, "index.html")
    if not os.path.exists(index_file) or os.path.getsize(index_file) < 100:
        print("[!] index.html chưa có hoặc rỗng. OpenCode tạo dự phòng...")
        # Tạo fallback standalone index.html chất lượng cao nếu opencode chưa lưu file
        run_cmd(f"{OPENCODE_BIN} run \"Ghi toàn bộ code game vào file {index_file}\" --model zai-coding-plan/glm-5.3", cwd=game_dir)

    print("=== [4/5] Kiểm thử & Verify Artifacts ===")
    if os.path.exists(index_file):
        size = os.path.getsize(index_file)
        print(f"[✓] File index.html hợp lệ ({size} bytes).")
    else:
        print("[!] Không tìm thấy index.html!")
        return 1

    print("=== [5/5] Cập nhật README & Push lên GitHub ===")
    # Cập nhật README.md
    readme_path = os.path.join(REPO_DIR, "README.md")
    with open(readme_path, "r", encoding="utf-8") as f:
        readme_content = f.read()
        
    game_row = f"| [`{slug}`](./games/{slug}/) | **{title}** | {genre} — {description[:60]}... | ✅ Ready |"
    if slug not in readme_content:
        # Chèn vào dưới header bảng
        table_marker = "|---|---|---|---|\n"
        if table_marker in readme_content:
            parts = readme_content.split(table_marker)
            new_readme = parts[0] + table_marker + game_row + "\n" + parts[1].replace("| *(Games will be added automatically via pipeline)* | | | |\n", "")
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(new_readme)

    # Git commit & push
    run_cmd("git config user.name 'Minh' && git config user.email 'minhgv@users.noreply.github.com'")
    run_cmd(f"git add games/{slug} README.md")
    run_cmd(f"git commit -m 'feat({slug}): autonomous delivery of {title} (GLM-5.3 + OpenCode)'")
    push_out, push_ret = run_cmd("git push origin main")
    print(f"[✓] Git Push thành công: {push_out}")
    print(f"\n🎉 HOÀN TẤT PIPELINE! Link game trên repo: https://github.com/minhgv/glm-h5-game/tree/main/games/{slug}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
